# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 18:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Log', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.AddField(
            model_name='user',
            name='hired_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='%m/%d/%Y'),
            preserve_default=False,
        ),
    ]
