# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 21:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Log', '0002_auto_20170127_1023'),
        ('black', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='all_items',
        ),
        migrations.AddField(
            model_name='items',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='people', to='Log.User'),
            preserve_default=False,
        ),
    ]
